# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.IntegerField(choices=[(1, 'Empty'), (2, 'Using'), (3, 'Repair'), (4, 'Stop Using')], default=1, verbose_name='Status')),
                ('eui', models.CharField(max_length=32)),
                ('mac', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpark.Parking')),
            ],
        ),
    ]
