# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='last_parking_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='eui',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='mac',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
