# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0002_auto_20160621_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='last_parking_time',
            new_name='last_park_time',
        ),
    ]
